import type { Metadata } from "next";
import Link from "next/link";
export const metadata:Metadata={title:"About Alyvero",description:"Learn what Alyvero does, how its browser-first file tools work and how Alyvero relates to FixTech."};
export default function About(){return <div className="container content-page">
<p className="eyebrow">Alyvero / about</p><h1>Useful file tools, without the clutter.</h1>
<p className="lead">Alyvero is a practical online utility platform for common digital file problems. The goal is simple: when you need to convert, compress, resize or create a file, the relevant tool should be easy to find and straightforward to use.</p>
<h2>What Alyvero does</h2><p>Alyvero currently focuses on PDF and image tasks including PDF to Word, PDF compression, PDF merging and splitting, PDF to JPG, image compression, HEIC to JPG, Image to PDF, image resizing and JPG to PNG conversion. Each tool has a specific job rather than being part of a directory of unrelated software.</p>
<h2>Part of FixTech</h2><p>Alyvero is a product of <a href="https://www.fixtech.co.ke" target="_blank" rel="noopener noreferrer">FixTech</a>, created and operated by Robert Indodi. FixTech and Alyvero have the same owner and founder. The two projects have different jobs: FixTech is an independent technology publication focused on explaining and troubleshooting technology problems, while Alyvero provides focused browser-based tools for solving common PDF and image file problems.</p><h2>Browser-first where practical</h2><p>Where the selected tool supports it, processing happens directly in the browser. This can reduce the need to create an account or send a file to a remote server. Each tool page explains its processing expectations, supported formats and limitations.</p>
<h2>How we build the tools</h2><ul><li>Clear descriptions instead of exaggerated promises.</li><li>Supported formats and limitations shown before processing.</li><li>No forced registration for the core tools.</li><li>Separate result files rather than silently replacing originals.</li><li>Simple navigation built around the task a person came to complete.</li></ul>
<h2>Built for practical situations</h2><p>Alyvero is intended for everyday jobs: preparing a document for an upload portal, reducing a photo before sending it, converting a phone photo from HEIC to JPG, resizing an image, or combining several files into one document.</p>
<h2>Part of the FixTech ecosystem</h2><p>Alyvero is powered by <a href="https://www.fixtech.co.ke" target="_blank" rel="noopener noreferrer">FixTech</a>, an independent technology resource. The two projects have different jobs: FixTech explains technology problems; Alyvero provides focused tools for solving file problems.</p>
<h2>Questions and feedback</h2><p>Found a problem or have a useful suggestion? <Link href="/contact">Contact Alyvero</Link>.</p>
</div>}