export const metadata={title:"Privacy Policy | Alyvero",description:"Alyvero privacy policy covering file processing, contact information, cookies, analytics and advertising."};
export default function Privacy(){return <div className="container content-page">
<p className="eyebrow">Alyvero / privacy</p><h1>Privacy Policy</h1><p className="lead"><strong>Last updated: September 26, 2026</strong><br/>This page explains what information may be handled when you use Alyvero and how file processing differs from ordinary site functions such as contact forms, analytics and advertising.</p>
<h2>1. About this policy</h2><p>Alyvero provides browser-based utilities for converting, compressing and creating digital files. This policy explains what information may be processed when you use Alyvero, how it is used and the choices available to you.</p>
<h2>2. Files you process</h2><p>Alyvero is designed to process files locally in your browser whenever a tool supports local processing. When local processing is used, the selected file is processed by your device and is not uploaded to Alyvero merely because you selected it. The exact processing method can vary by tool, so read the relevant tool page before processing.</p><p>Do not upload or process confidential, highly sensitive or regulated information unless you have assessed that the service is appropriate for that information.</p>
<h2>3. Contact information</h2><p>If you use the contact form, the information you submit, such as your name, email address and message, is transmitted through FormSubmit and delivered to the Alyvero operator to respond to your request, handle support issues, receive feedback or discuss partnerships.</p>
<h2>4. Cookies and similar technologies</h2><p>Alyvero may use cookies, local storage or similar technologies for essential site functions, security, analytics and advertising. Some technologies may be provided by third-party services.</p>
<h2>5. Analytics</h2><p>If analytics services are enabled, Alyvero may collect information such as pages visited, approximate usage patterns, device or browser information and referring pages. Alyvero does not intend to collect the contents of files being processed as analytics data.</p>
<h2>6. Advertising and Google AdSense</h2><p>Alyvero may display advertising, including Google AdSense. If an advertising provider serves ads, third parties may use cookies, web beacons, IP addresses or similar identifiers to serve, measure or personalize advertising in accordance with their policies and applicable law.</p><p>Users can manage Google's personalized advertising settings through <a href="https://adssettings.google.com/" target="_blank" rel="noreferrer">Google Ads Settings</a>. Where required for users in the EEA, UK or Switzerland, Alyvero will use the applicable Google-certified consent mechanism before serving personalized advertising.</p>
<h2>7. Third-party services</h2><p>Alyvero may use third-party services for form delivery, hosting, analytics, advertising and security. Those providers may process information according to their own privacy policies.</p>
<h2>8. Data security and retention</h2><p>Alyvero takes reasonable steps to protect information handled by the service. Contact-form information may be retained as reasonably necessary to respond, maintain business records or resolve disputes. Browser-local file processing does not create an Alyvero file copy unless the relevant tool explicitly states otherwise.</p>
<h2>9. Children's privacy</h2><p>Alyvero is a general-purpose utility service and is not directed specifically at children. Do not submit personal information through the contact form unless you are permitted to do so.</p>
<h2>10. Your choices and requests</h2><p>You can stop using Alyvero at any time. Where applicable, you may request information about personal data submitted directly to Alyvero or ask for correction or deletion, subject to legal and operational requirements.</p>
<h2>11. Policy changes</h2><p>This policy may be updated when Alyvero adds features, analytics, advertising or other services. The latest version will be published on this page with an updated date.</p>
<h2>12. Contact</h2><p>For privacy questions or requests, use the <a href="/contact">Alyvero contact form</a>.</p>
</div>