export const metadata={title:"Privacy Policy | Alyvero",description:"Alyvero privacy policy covering files, contact forms, cookies, analytics, advertising and third-party services."};
export default function Privacy(){return <div className="container content-page">
<p className="eyebrow">Alyvero / privacy</p><h1>Privacy Policy</h1><p className="lead"><strong>Last updated: October 1, 2026</strong><br/>This policy explains what information Alyvero handles when you use the website and its file tools, including file processing, contact forms, analytics, cookies and advertising.</p>
<h2>1. About Alyvero</h2><p>Alyvero provides browser-based utilities for converting, compressing, resizing and creating digital files. The service is operated as a focused online utility platform and does not require an account for its core tools.</p>
<h2>2. Files you process</h2><p>Many Alyvero tools are designed to process files locally in your browser. When a tool performs local processing, selecting a file does not by itself send that file to Alyvero's servers. Processing can vary by tool, browser and file type, so the relevant tool page should be read before use.</p><p>Alyvero does not promise that every tool is completely offline or that every browser will handle every file identically. Keep original copies of important files and do not process confidential or regulated information unless you have independently determined that the workflow is appropriate.</p>
<h2>3. Information submitted through the contact form</h2><p>If you use the contact form, the name, email address and message you submit are sent through FormSubmit, a third-party form delivery service, and delivered to the Alyvero operator. This information is used to answer questions, investigate reported problems, respond to feedback and handle partnership enquiries.</p><p>Do not include passwords, payment information, private keys, confidential documents or other sensitive information in a contact-form message.</p>
<h2>4. Cookies and similar technologies</h2><p>Alyvero may use cookies, local storage and similar technologies for essential functionality, security and advertising. Third-party providers may set or access their own identifiers when their services are used on the site.</p>
<h2>5. Analytics</h2><p>Alyvero does not currently rely on a third-party analytics script in the site-wide page layout. If analytics are enabled in the future, information such as pages visited, referring pages, approximate usage patterns, browser or device information and technical request data may be processed. Alyvero does not intend to use analytics to collect the contents of files processed locally in your browser.</p>
<h2>6. Advertising and Google AdSense</h2><p>Alyvero may display advertising through Google AdSense and other advertising services. Advertising providers may use cookies, IP addresses, web beacons or similar technologies to deliver, measure or personalize advertising, subject to their policies and applicable law.</p><p>Google's advertising technologies may process information associated with a user's browser or device. Google provides controls for advertising personalization through <a href="https://adssettings.google.com/" target="_blank" rel="noopener noreferrer">Google Ads Settings</a>. Google also explains how it uses information when users visit sites or apps that use its services through its <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener noreferrer">partner-site data-use information</a>.</p><p>For users in the EEA, UK and Switzerland, Alyvero will use the applicable Google-certified consent mechanism required for personalized advertising and related storage/access technologies before those technologies are used where consent is legally required. Advertising and consent features can change as the service develops.</p>
<h2>7. Third-party services</h2><p>Alyvero uses or may use third-party services for hosting, form delivery, analytics, advertising, security and other site functions. Those providers process information under their own terms and privacy policies. Alyvero does not control the privacy practices of independent third parties.</p>
<h2>8. Data security and retention</h2><p>Alyvero takes reasonable steps to protect information under its control. Contact-form information may be retained for as long as reasonably necessary to respond to requests, maintain appropriate business records, investigate abuse or resolve disputes. Browser-local file processing does not create an Alyvero server-side file copy unless a specific tool explicitly states otherwise.</p>
<h2>9. Children's privacy</h2><p>Alyvero is a general-purpose utility service and is not specifically directed to children. Users should not submit personal information through the contact form unless they are permitted to do so.</p>
<h2>10. Your choices and privacy requests</h2><p>You may stop using Alyvero at any time. Where applicable, you may request access to, correction of or deletion of personal information that you submitted directly to Alyvero, subject to legal, security and operational requirements.</p>
<h2>11. Changes to this policy</h2><p>Alyvero may update this policy when its tools, analytics, advertising or other services change. The current version and its effective date are published on this page.</p>
<h2>12. Contact</h2><p>For privacy questions or requests, use the <a href="/contact">Alyvero contact form</a>.</p>
</div>}