export type ToolInfo={slug:string;name:string;description:string;longDescription:string;supported:string[];notes:string;faqs:{question:string;answer:string}[]};
export const tools:ToolInfo[]=[
{slug:"pdf-to-word",name:"PDF to Word",description:"Convert text-based PDF files into editable Word documents in your browser.",longDescription:"PDF to Word is designed for text-based PDFs that need to be edited in Microsoft Word or another DOCX-compatible editor.",supported:["Text-based PDF files","DOCX output"],notes:"Scanned or image-only PDFs may not convert correctly because this tool does not promise full OCR.",faqs:[{question:"Can I convert a scanned PDF?",answer:"This tool is intended for text-based PDFs. Scanned PDFs may require OCR."},{question:"Do I need an account?",answer:"No Alyvero account is required."}]},
{slug:"compress-pdf",name:"Compress PDF",description:"Reduce PDF file size in your browser for easier uploading, emailing or sharing.",longDescription:"Compress PDF re-saves supported PDF files to reduce unnecessary file overhead. Already-optimized PDFs may show little or no reduction.",supported:["PDF input","PDF output"],notes:"This MVP does not promise aggressive image recompression.",faqs:[{question:"Will every PDF become smaller?",answer:"No. Some PDFs are already optimized."},{question:"Does compression change the PDF?",answer:"The tool creates a new PDF file."}]},
{slug:"compress-image",name:"Compress Image",description:"Reduce JPG, PNG or WebP image file size in your browser.",longDescription:"Compress Image lets you choose an image and adjust compression quality before creating a smaller copy.",supported:["JPG","PNG","WebP"],notes:"Lower quality can produce a smaller file but may reduce visual detail.",faqs:[{question:"Can I choose the compression quality?",answer:"Yes."},{question:"Is my original image changed?",answer:"No. Alyvero creates a separate result."}]},
{slug:"heic-to-jpg",name:"HEIC to JPG",description:"Convert HEIC photos into JPG images directly in your browser.",longDescription:"Useful when a device produces HEIC images but a website or recipient expects JPG.",supported:["HEIC input","JPG output","Multiple files"],notes:"Conversion support can vary with browser capabilities and the source file.",faqs:[{question:"Can I convert multiple HEIC files?",answer:"Yes."},{question:"Why convert HEIC to JPG?",answer:"JPG is widely supported."}]},
{slug:"image-to-pdf",name:"Image to PDF",description:"Combine one or more JPG or PNG images into a PDF in your browser.",longDescription:"Turns selected JPG or PNG images into a single PDF document.",supported:["JPG","PNG","Multiple images","PDF output"],notes:"Page sizing is handled automatically.",faqs:[{question:"Can I combine several images?",answer:"Yes."},{question:"Are the original images changed?",answer:"No."}]},
{slug:"merge-pdf",name:"Merge PDF",description:"Combine multiple PDF files into one PDF in your browser.",longDescription:"Merge several PDFs into one document while keeping the selected file order.",supported:["PDF input","Multiple files","PDF output"],notes:"Check the final page order before sharing or submitting.",faqs:[{question:"Can I merge more than two PDFs?",answer:"Yes."}]},
{slug:"split-pdf",name:"Split PDF",description:"Split a PDF into separate one-page PDF files in your browser.",longDescription:"Creates one PDF file for each page of the selected document.",supported:["PDF input","One PDF per page"],notes:"Very large documents may use more browser memory.",faqs:[{question:"Does it split every page?",answer:"Yes. Each page becomes its own PDF."}]},
{slug:"pdf-to-jpg",name:"PDF to JPG",description:"Convert PDF pages into JPG images directly in your browser.",longDescription:"Renders each PDF page as a separate JPG image.",supported:["PDF input","JPG output","One image per page"],notes:"Large or image-heavy PDFs may use significant browser memory.",faqs:[{question:"Does every page become a JPG?",answer:"Yes."}]},
{slug:"resize-image",name:"Resize Image",description:"Resize JPG, PNG or WebP images in your browser.",longDescription:"Change image width while preserving the original aspect ratio.",supported:["JPG","PNG","WebP","JPG output"],notes:"The current tool exports the resized result as JPG.",faqs:[{question:"Will proportions stay the same?",answer:"Yes. Height is calculated from the original aspect ratio."}]},
{slug:"jpg-to-png",name:"JPG to PNG",description:"Convert JPG images to PNG directly in your browser.",longDescription:"JPG to PNG converts a JPG image into a PNG copy locally in your browser.",supported:["JPG input","PNG output"],notes:"The original JPG is not changed. PNG output can be larger than the source because it uses lossless compression.",faqs:[{question:"Is my original JPG changed?",answer:"No. Alyvero creates a separate PNG result."},{question:"Does PNG always make the file smaller?",answer:"No. PNG is lossless and can be larger than a JPG."}]}
] as const;